import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div
    // className={styles.container}
    >
      <Head>
        <title>DHK - Kizjien</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main
      // className={styles.main}
      >
        <Link href='/about'>
          <a
          // className={styles.link}
          >
            About
          </a>
        </Link>
      </main>

      <footer
      // className={styles.footer}
      ></footer>
    </div>
  )
}
