import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/layout/Layout'

export default function Home() {
  return (
    <div>
      <Layout home title='DHK - Kizjien'>
        <Head>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main>
          <Link href='/about'>
            <a className='visitors-btn--secondary'>About</a>
          </Link>
        </main>

        <footer>Footer</footer>
      </Layout>
    </div>
  )
}
